### ISSUE TITLE
Issue handling missing <symmetry> with inv2dlsv / fseed.py

### ISSUE THREAD

**Issue by sheimers** [SeisComP/extras#5]
We encountred an issue with inv2dlsv processing an xml file with missing symmetry tags in the FIR filter section of dataloggers. I think it is optional in the Seiscomp xml (according to  seiscomp3_generic.xml), so not an error in the input file.

What happens: The generated dataless has an empty string for the symmetry. If I open it in PDCC, it gives a warning and replaces it with 'Z'. If I use rdseed to convert it to RESP files it will produce an invalid character for the symmerty in the RESP file.

For us I solved it with a small patch to fseed.py

```
class _Blockette61(object):
    def __init__(self, name, symmetry, input_units, output_units, ncoeff,
        coeff):

        #fix bug with empty symmetry (by Stefan Heimers)
        if (symmetry == ''):
            print ("Symmetry empty, assuming 'A'")
            symmetry = 'A'
        
        self.__stage = 0
        self.__name = _mkseedstring(61, 4, name, 1, 25, "UN")
        self.__symmetry = _mkseedstring(61, 5, symmetry, 1, 1, "U")

```

...and the same for Blockette41

Can one of the developpers please review this, and if considered useful maybe integrate it in a future version, or propose a better solution?

**Comment by gempa-jabe** [comment]
Thanks Stefan for the patch. Actually `fseed.py` is deprecated in the same way as dataless SEED is. But the problem moves on with any format conversion. Any optional attribute (and there are many in SeisComP inventory) needs to be set to a default if unset for any target format that does not support optionals. So, if 'A' is a decent default for symmetry then I agree with the patch. Maybe @andres-h  can comment on this. But actually this needs to be done for many other attributes as well. I personally would prefer to quit and ignore that station / channel and ask the user to populate the field in SeisComP XML to avoid assumptions and misunderstandings.

**Comment by sheimers** [comment]
We actually don't need dataless seed, it's only an intermediate step to generate RESP files for SQLX using rdseed. Is there a direct way to generate RESP from Seiscomp inventory? Then we'd no longer care about fseed.py.

**Comment by andres-h** [comment]
> Is there a direct way to generate RESP from Seiscomp inventory?

No, but if there was, it would have the same problem with undefined symmetry, etc. IIRC, all inventory attributes are left optional, because whether an attribute is required or not depends on a use case.

I actually think there is a mistake in _mkseedstring(), because empty value should not be allowed with "U" flag. I'll try to fix this.
